// state.js 
export default {
  cod: [],
  csgo: [],
  lol: [],
  val: [],
  dota: [],
  halo: [],
  isLoading: false,
  filteredData: {
    slips: {
      cod: [],
      csgo: [],
      val: [],
      halo: [],
      isLoading: false,
    },
    pairs: {
      cod: [],
      csgo: [],
      val: [],
      lol: [],
      halo: [],
      isLoading: false,
    },
    base: {
      cod: [],
      csgo: [],
      val: [],
      halo: [],
      lol: [],
    },
    isLoading: false,
    searchText: "",
    filterSet: [],
  },
  slips: {
    cod: [],
    csgo: [],
    val: [],
    halo: [],
    isLoading: false,
  },
  pairs: {
    cod: [],
    csgo: [],
    val: [],
    lol: [],
    halo: [],
    isLoading: false,
  },
  used: [],
  userData: {
    isLoggedIn: false,
    isAdmin: false,
    email: null,
  },
  showHeadshot: localStorage.getItem("showHeadshot") === "true",
};
